FROM mcr.microsoft.com/dotnet/sdk:10.0.100 AS build
WORKDIR /src
COPY . .
ARG PROJECT
RUN dotnet restore "$PROJECT"
RUN dotnet publish "$PROJECT" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0.12
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
ARG ASSEMBLY
ENV VERTX_ASSEMBLY=$ASSEMBLY
COPY --from=build /app/publish .
USER app
ENTRYPOINT ["sh", "-c", "dotnet \"$VERTX_ASSEMBLY\""]
